In [ ]:
from google.colab import drive
drive.mount('content')
%cd content/"My Drive"/daf/data

Drive already mounted at content; to attempt to forcibly remount, call drive.mount("content", force_remount=True).
/content/content/My Drive/daf/data


In [ ]:
!pip install transformers
!pip install nlpaug numpy matplotlib python-dotenv
!pip install knockknock
!pip install efficientnet_pytorch
!pip install pytorch-lightning
!pip install --upgrade wandb
!wandb login 2518ba7a9102f96fd5d82aea1e7fcf1cba49eff5
opt_level = 'O1'

Requirement already up-to-date: wandb in /usr/local/lib/python3.6/dist-packages (0.9.3)
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
Successfully logged in to Weights & Biases!


In [ ]:
import nltk
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [ ]:
import pandas as pd
train = pd.read_json('train.jsonl',lines=True)
dev = pd.read_json('dev.jsonl',lines=True)
test = pd.read_json('test.jsonl',lines=True)

In [ ]:
max([len(sen) for sen in train.text])

433

In [ ]:
import os
import torch
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, utils
import albumentations
from albumentations import (
    HorizontalFlip, IAAPerspective, ShiftScaleRotate, CLAHE, RandomRotate90,
    Transpose, ShiftScaleRotate, Blur, OpticalDistortion, GridDistortion, HueSaturationValue,
    IAAAdditiveGaussianNoise, GaussNoise, MotionBlur, MedianBlur, IAAPiecewiseAffine,
    IAASharpen, IAAEmboss, RandomBrightnessContrast, Flip, OneOf, Compose, RandomCrop, Resize, Normalize
)
from albumentations.pytorch import ToTensor
from keras.preprocessing.sequence import pad_sequences# Set the maximum sequence length.
from transformers import BertTokenizer, RobertaTokenizer # Load the BERT tokenizer.
print('Loading BERT tokenizer...')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)
# tokenizer = RobertaTokenizer.from_pretrained('roberta-base', do_lower_case=True)

class Memes(Dataset):

    def __init__(self, csv_file, root_dir, transform=None, aug=None, text_aug=None):
        """
        Args:
            csv_file (string): Path to the csv file with annotations.
            root_dir (string): Directory with all the images.
            transform (callable, optional): Optional transform to be applied
                on a sample.
        """
        self.file = pd.read_json(csv_file,lines=True)
        self.root_dir = root_dir
        self.transform = transform
        self.aug = aug
        self.text_aug = text_aug
        
    def __len__(self):
        return len(self.file)

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()

        img_name = os.path.join(self.root_dir,
                                self.file.iloc[idx, 1])
        image = Image.open(img_name).convert('RGB')
        label = self.file.iloc[idx, 2]
        label = np.array([label])
        text = self.file.iloc[idx, 3]
        if self.text_aug:
            text = self.text_aug.augment(text)
        encoded_sent = tokenizer.encode(
             text, # Sentence to encode.
             add_special_tokens = True, # Add '[CLS]' and '[SEP]' # This function also supports truncation and conversion
             # to pytorch tensors, but we need to do padding, so we
             # can't use these features :( .
             #max_length = 128, # Truncate all sentences.
             #return_tensors = 'pt', # Return pytorch tensors.
             )
        # I've chosen 64 somewhat arbitrarily. It's slightly larger than the
        # maximum training sentence length of 47...
        MAX_LEN = 433
        #print('\nPadding/truncating all sentences to %d values...' % MAX_LEN)
        #print('\nPadding token: "{:}", ID: {:}'.format(tokenizer.pad_token, tokenizer.pad_token_id))# Pad our input tokens with value 0.
        # "post" indicates that we want to pad and truncate at the end of the sequence,
        # as opposed to the beginning.
        encoded_sent = pad_sequences([encoded_sent], maxlen=MAX_LEN, dtype="long", 
         value=0, truncating="post", padding="post")
        #print('\Done.')
        attention_masks=[]
        #print(encoded_sent)
        att_mask = [int(token_id > 0) for token_id in encoded_sent[0]]
        attention_masks.append(att_mask)
        encoded_sent = torch.tensor(encoded_sent)
        attention_masks = torch.tensor(attention_masks)
        label = torch.tensor(label)
        image=np.array(image)
        if self.aug:
            image = self.aug(image=image)['image']
        image = self.transform(image=image)['image']
        sample = {'name':img_name,'image': image,'text':encoded_sent[0],'mask':attention_masks[0],'label': label}
        return sample

class Test(Dataset):

    def __init__(self, csv_file, root_dir, transform=None):
        """
        Args:
            csv_file (string): Path to the csv file with annotations.
            root_dir (string): Directory with all the images.
            transform (callable, optional): Optional transform to be applied
                on a sample.
        """
        self.file = pd.read_json(csv_file,lines=True)
        self.root_dir = root_dir
        self.transform = transform
        
    def __len__(self):
        return len(self.file)

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()

        img_name = os.path.join(self.root_dir,
                                self.file.iloc[idx, 1])
        image = Image.open(img_name).convert('RGB')
        text = self.file.iloc[idx, 2]
        encoded_sent = tokenizer.encode(
             text, # Sentence to encode.
             add_special_tokens = True, # Add '[CLS]' and '[SEP]' # This function also supports truncation and conversion
             # to pytorch tensors, but we need to do padding, so we
             # can't use these features :( .
             #max_length = 128, # Truncate all sentences.
             #return_tensors = 'pt', # Return pytorch tensors.
             )
        # I've chosen 64 somewhat arbitrarily. It's slightly larger than the
        # maximum training sentence length of 47...
        MAX_LEN = 433
        #print('\nPadding/truncating all sentences to %d values...' % MAX_LEN)
        #print('\nPadding token: "{:}", ID: {:}'.format(tokenizer.pad_token, tokenizer.pad_token_id))# Pad our input tokens with value 0.
        # "post" indicates that we want to pad and truncate at the end of the sequence,
        # as opposed to the beginning.
        encoded_sent = pad_sequences([encoded_sent], maxlen=MAX_LEN, dtype="long", 
         value=0, truncating="post", padding="post")
        #print('\Done.')
        attention_masks=[]
        #print(encoded_sent)
        att_mask = [int(token_id > 0) for token_id in encoded_sent[0]]
        attention_masks.append(att_mask)
        encoded_sent = torch.tensor(encoded_sent)
        attention_masks = torch.tensor(attention_masks)
        image=np.array(image)
        image = self.transform(image=image)['image']
        sample = {'name':img_name,'image': image,'text':encoded_sent[0],'mask':attention_masks[0]}
        return sample


Using TensorFlow backend.


Loading BERT tokenizer...


In [ ]:
import nlpaug.augmenter.char as nac
import nlpaug.augmenter.word as naw
import nlpaug.augmenter.sentence as nas
import nlpaug.flow as naf

from nlpaug.util import Action

text_augs = naf.Sometimes([
    nac.RandomCharAug(action="delete"),
    nac.RandomCharAug(action="insert"),
    naw.RandomWordAug(),
    naw.ContextualWordEmbsAug(
    model_path='roberta-base', action="insert"),
    naw.ContextualWordEmbsAug(model_path='bert-base-multilingual-uncased', action="insert"),
    naw.ContextualWordEmbsAug(
    model_path='bert-base-uncased', action="substitute"),
    naw.ContextualWordEmbsAug(model_path='bert-base-multilingual-uncased', action="substitute"),
    naw.SynonymAug(aug_src='wordnet', lang='eng'),
    naw.ContextualWordEmbsAug(
    model_path='distilbert-base-uncased', action="substitute"),
    naw.SynonymAug(aug_src='wordnet')
])

augs = albumentations.Compose([
        RandomRotate90(),
        Flip(),
        Transpose(),
        HorizontalFlip(p=0.5),
        OneOf([
            IAAAdditiveGaussianNoise(),
            GaussNoise(),
        ], p=0.2),
        OneOf([
            MotionBlur(p=0.2),
            MedianBlur(blur_limit=3, p=0.1),
            Blur(blur_limit=3, p=0.1),
        ], p=0.2),
        ShiftScaleRotate(shift_limit=0.0625, scale_limit=0.2, rotate_limit=45, p=0.2),
        OneOf([
           CLAHE(clip_limit=2),
           IAASharpen(),
           IAAEmboss(),
           RandomBrightnessContrast(),
        ], p=0.3),
        HueSaturationValue(p=0.3),
    ], p=0.5)

data_transform = Compose([
    Resize(224,224), 
    Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225],
    ),ToTensor()
])
val_transform = Compose([
    Resize(224,224), 
    Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225],
    ),ToTensor()
])
train = Memes(csv_file='pred_augs3.jsonl',
                                    root_dir='',transform=data_transform,aug=augs)
val = Memes(csv_file='dev.jsonl',root_dir='',transform=val_transform)
test = Test(csv_file='test.jsonl',root_dir='',transform=val_transform)
dataset_sizes = {'train':len(train), 'val':len(val)}

train = DataLoader(train, batch_size=6,
                        shuffle=True)
val = DataLoader(val, batch_size=4,
                        shuffle=True)
test = DataLoader(test, batch_size=1,
                        shuffle=False)
dataloaders = {'train':train,'val':val}

Some weights of RobertaForMaskedLM were not initialized from the model checkpoint at roberta-base and are newly initialized: ['lm_head.decoder.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of the model checkpoint at bert-base-multilingual-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForMaskedLM were not initialized from the model checkpoint at bert-base-m

In [ ]:

#for i_batch, sample in enumerate(test):

#    print(i_batch, sample['image'].shape, sample['text'].size(),sample['mask'].size())

#    if i_batch == 3:
#       break



In [ ]:
import copy
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
import torchvision
from torchvision import models
from sklearn.metrics import roc_auc_score
from tqdm.notebook import tqdm as tqdm
import pytorch_lightning.metrics.sklearns as plm

from knockknock import slack_sender


import wandb

wandb.init(project="hateful_memes")

%load_ext tensorboard
device = 'cuda'

@slack_sender(webhook_url='https://hooks.slack.com/services/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', channel="model_training")
def send_my_epochs(epoch,losses,aucs):
    return {'Epoch':epoch, 'Epoch loss': losses, 'Epoch AUC':aucs}
@slack_sender(webhook_url='https://hooks.slack.com/services/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', channel="model_training")
def train_model(model, criterion, optimizer, scheduler, num_epochs=25):
    since = time.time()
    met1 = plm.Accuracy(normalize=True)
    met2 = plm.F1()
    met3 = plm.Recall(average = 'macro')
    cm = plm.ConfusionMatrix()
    best_model_wts = copy.deepcopy(model.state_dict())
    best_loss = np.inf
    best_roc = 0.0
    best_acc = 0.0
    best_prec = 0.0
    best_recall = 0.0
    train_losses = []
    valid_losses = []
    wandb.watch(model)
    for epoch in range(num_epochs):
        print('Epoch {}/{}'.format(epoch+1, num_epochs))
        print('-' * 10)

        # Each epoch has a training and validation phase
        for phase in ['train', 'val']:
            if phase == 'train':
                model.train()  # Set model to training mode
            else:
                model.eval()   # Set model to evaluate mode

            running_loss = 0.0
            running_acc = 0.0
            running_prec = 0.0
            running_recall = 0.0
            runnin_roc = 0.0
            running_labels = []
            running_preds = []
            running_probs = []
            tk0 = tqdm(dataloaders[phase], total=dataset_sizes[phase]//dataloaders[phase].batch_size +1)
            counter = 0
            # Iterate over data.
            for i,sample in enumerate(tk0,0):
                inputs = sample['image']
                
                texts = sample['text']
                #print(texts)
                offsets = sample['mask']
                labels = sample['label']
                inputs = inputs.to(device='cuda')
                texts = texts.to(device='cuda')
                offsets = offsets.to(device='cuda')
                labels = labels.to(device='cuda')

                # zero the parameter gradients
                optimizer.zero_grad()

                # forward
                # track history if only in train
                with torch.set_grad_enabled(phase == 'train'):
                    outputs = model(inputs,texts,offsets)
                    #print(labels)
                    #print(outputs)            
                    _, preds = torch.max(outputs, 1)
                    probs = []
                    for i in range(len(_)):
                        if preds[i]==0:
                            probs.append(1-np.exp(_[i].cpu().item()))
                        else:
                            probs.append(np.exp(_[i].cpu().item()))
                    #print(labels.shape)
                    #smooth_label = smooth_one_hot(label,2,0.1)
                    #loss = criterion(outputs, smooth_label)

                    loss = criterion(outputs, labels.squeeze(1))
                    acc = met1(preds, labels)
                    prec = met2(preds, labels)
                    recall = met3(preds, labels)
                    # backward + optimize only if in training phase
                    if phase == 'train':
                        loss.backward()
                        optimizer.step()

                # statistics
                running_loss += loss.item() * inputs.size(0)
                running_acc += acc.item()
                running_prec += prec.item()
                running_recall += recall.item()
                running_labels.extend(labels.squeeze(1).cpu())
                running_probs.extend(probs)
                running_preds.extend(preds.cpu())
                counter+=1
                tk0.set_postfix(loss=(running_loss / (counter * dataloaders[phase].batch_size)))
                #print(_)
                #print(preds)
                #print(labels.squeeze(1))
            if phase == 'train':
                scheduler.step()

            if phase == 'val':
                print(cm(np.array(running_preds),np.array(running_labels)))
            epoch_loss = running_loss / dataset_sizes[phase]
            epoch_acc = running_acc / dataset_sizes[phase]
            epoch_prec = running_prec / dataset_sizes[phase]
            epoch_recall = running_recall / dataset_sizes[phase]
            epoch_roc = roc_auc_score(running_labels,running_probs)

            if phase == 'train':
                wandb.log({"Train ROC_AUC": epoch_roc, "Train Loss": epoch_loss})
                
            if phase == 'val':
                wandb.log({"Test ROC_AUC": epoch_roc, "Test Loss": epoch_loss})
                    
            print('{} Loss: {:.4f} Accuracy: {:.4f} Precision: {:.4f} Recall: {:.4f} AUC: {:.4f}'.format(
                phase, epoch_loss, epoch_acc, epoch_prec, epoch_recall, epoch_roc))
            # deep copy the model
            if phase == 'val' and epoch_roc > best_roc:
                best_loss = epoch_loss
                best_acc = epoch_acc
                best_prec = epoch_prec
                best_recall = epoch_recall
                best_roc = epoch_roc
                best_model_wts = copy.deepcopy(model.state_dict())
                model.load_state_dict(best_model_wts)

        print()

    time_elapsed = time.time() - since
    print('Training complete in {:.0f}m {:.0f}s'.format(
        time_elapsed // 60, time_elapsed % 60))
    print('Best val loss: {:4f}'.format(best_loss))
    print('Best val AUC: {:4f}'.format(best_roc))
    print('Best val accuracy: {:4f}'.format(best_acc))
    print('Best val recall: {:4f}'.format(best_recall))
    print('Best val prec: {:4f}'.format(epoch_prec))

    # load best model weights
    # model.load_state_dict(best_model_wts)
    # torch.save(model,'bert_dec.pt')
    return {'loss':best_loss, 'AUC':best_roc,'model':model}

Custom Functions

In [ ]:
class Swish(torch.autograd.Function):
    @staticmethod
    def forward(ctx, i):
        result = i*i.sigmoid()
        ctx.save_for_backward(result,i)
        return result

    @staticmethod
    def backward(ctx, grad_output):
        result,i = ctx.saved_variables
        sigmoid_x = i.sigmoid()
        return grad_output * (result+sigmoid_x*(1-result))

swish= Swish.apply

class Swish_module(nn.Module):
    def forward(self,x):
        return swish(x)
    
swish_layer = Swish_module()
def smooth_one_hot(true_labels: torch.Tensor, classes: int, smoothing=0.0):
    """
    if smoothing == 0, it's one-hot method
    if 0 < smoothing < 1, it's smooth method

    """
    assert 0 <= smoothing < 1
    confidence = 1.0 - smoothing
    label_shape = torch.Size((true_labels.size(0), classes))
    with torch.no_grad():
        true_dist = torch.empty(size=label_shape, device=true_labels.device)
        true_dist.fill_(smoothing / (classes - 1))
        true_dist.scatter_(1, true_labels.data.unsqueeze(1), confidence)
    return true_dist

class LabelSmoothingLoss(nn.Module):
    def __init__(self, classes, smoothing=0.0, dim=-1):
        super(LabelSmoothingLoss, self).__init__()
        self.confidence = 1.0 - smoothing
        self.smoothing = smoothing
        self.cls = classes
        self.dim = dim

    def forward(self, pred, target):
        pred = pred.log_softmax(dim=self.dim)
        with torch.no_grad():
            # true_dist = pred.data.clone()
            true_dist = torch.zeros_like(pred)
            true_dist.fill_(self.smoothing / (self.cls - 1))
            true_dist.scatter_(1, target.data.unsqueeze(1), self.confidence)
        return torch.mean(torch.sum(-true_dist * pred, dim=self.dim))

In [ ]:
import torch
from torch.optim.optimizer import Optimizer, required


class Madam(Optimizer):

    def __init__(self, params, lr=0.01, p_scale=3.0, g_bound=10.0):

        self.p_scale = p_scale
        self.g_bound = g_bound
        defaults = dict(lr=lr)
        super(Madam, self).__init__(params, defaults)

    def step(self, closure=None):
        """Performs a single optimization step.
        Arguments:
            closure (callable, optional): A closure that reevaluates the model
                and returns the loss.
        """
        loss = None
        if closure is not None:
            loss = closure()

        for group in self.param_groups:
            for p in group['params']:
                if p.grad is None:
                    continue

                state = self.state[p]
                if len(state) == 0:
                    state['max'] = self.p_scale*(p*p).mean().sqrt().item()
                    state['step'] = 0
                    state['exp_avg_sq'] = torch.zeros_like(p)

                state['step'] += 1
                bias_correction = 1 - 0.999 ** state['step']
                state['exp_avg_sq'] = 0.999 * state['exp_avg_sq'] + 0.001 * p.grad.data**2
                
                g_normed = p.grad.data / (state['exp_avg_sq']/bias_correction).sqrt()
                g_normed[torch.isnan(g_normed)] = 0
                g_normed.clamp_(-self.g_bound, self.g_bound)
                
                p.data *= torch.exp( -group['lr']*g_normed*torch.sign(p.data) )
                p.data.clamp_(-state['max'], state['max'])

        return loss

In [ ]:
from transformers import BertForSequenceClassification,RobertaForSequenceClassification, AdamW, RobertaConfig
import torch.nn.functional as F
class Flatten(nn.Module):
    def forward(self, input):
        return input.view(input.size(0), -1)

from efficientnet_pytorch import EfficientNet
bert = BertForSequenceClassification.from_pretrained(
 "bert-base-uncased", # Use the 12-layer BERT model, with an uncased vocab.
 num_labels = 16, # The number of output labels--2 for binary classification.
 # You can increase this for multi-class tasks. 
 output_attentions = False, # Whether the model returns attentions weights.
 output_hidden_states = False, # Whether the model returns all hidden-states.
)
# roberta = RobertaForSequenceClassification.from_pretrained('roberta-base',
# num_labels = 2, # The number of output labels--2 for binary classification.
#  # You can increase this for multi-class tasks. 
# output_attentions = False, # Whether the model returns attentions weights.
# output_hidden_states = False, # Whether the model returns all hidden-states.
# )
model_ft = EfficientNet.from_pretrained('efficientnet-b0')
# model_ft = EfficientNet.from_name('efficientnet-b0')
# model_ft = models.vgg19(pretrained=True)
# model_ft = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
# modules=list(model_ft.children())[1:][:-2]
#print(modules)
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.features1 = nn.Sequential(model_ft)
        self.features = nn.Sequential(
            # Flatten(),
            swish_layer,nn.Dropout(0.32),nn.Linear(1000, 64),
            swish_layer,nn.Dropout(0.2),nn.Linear(64, 16))
        self.features2 = bert
        self.classifier = nn.Sequential(nn.Linear(32, 2))
        self.softmax = nn.LogSoftmax(dim=1)
    def forward(self, x1,x2,x3):
        #print(x1.dtype)    
        #print(x2.dtype)
        #print(x3.dtype)
        #x2 = x2.to(torch.int64)
        #print(x2.dtype)
       
        x1 = self.features1(x1)
        x1 = self.features(x1)
        x2 = self.features2(x2,x3)[0]
        x1 = x1.view(x1.size(0), -1)
        #print(x1)
        #print(x2)
        #print(x1.dtype)
        #print(x2.dtype)
        x = torch.cat((x1, x2), dim=1)
        x = self.classifier(x)
        x = self.softmax(x)
        return x


model = MyModel()
torch.cuda.empty_cache()
model.to('cuda')
criterion = nn.NLLLoss()
#criterion = LabelSmoothingLoss(classes=2)
# Observe that all parameters are being optimized
 # optimizer = Madam(model.parameters(), lr= 1.539374136412813e-04)
# Decay LR by a factor of 0.1 every 7 epochs
exp_lr_scheduler = lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.1)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

Loaded pretrained weights for efficientnet-b0


In [ ]:
import time
#print(model)
hist = train_model(model, criterion, optimizer, exp_lr_scheduler,
                       num_epochs=15)

Epoch 1/15
----------


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: 'saved_variables' is deprecated; use 'saved_tensors'
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.6492 Accuracy: 0.1046 Precision: 0.0756 Recall: 0.0923 AUC: 0.6025


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



tensor([[227.,  23.],
        [208.,  42.]])
val Loss: 0.7692 Accuracy: 0.1345 Precision: 0.1064 Recall: 0.1280 AUC: 0.6062

Epoch 2/15
----------


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: 'saved_variables' is deprecated; use 'saved_tensors'
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.5650 Accuracy: 0.1196 Precision: 0.1074 Recall: 0.1132 AUC: 0.7589


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



tensor([[201.,  49.],
        [170.,  80.]])
val Loss: 0.7793 Accuracy: 0.1405 Precision: 0.1195 Recall: 0.1353 AUC: 0.6275

Epoch 3/15
----------


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: 'saved_variables' is deprecated; use 'saved_tensors'
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.5129 Accuracy: 0.1251 Precision: 0.1149 Recall: 0.1202 AUC: 0.8131


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



tensor([[219.,  31.],
        [205.,  45.]])
val Loss: 0.9008 Accuracy: 0.1320 Precision: 0.1069 Recall: 0.1301 AUC: 0.6218

Epoch 4/15
----------


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: 'saved_variables' is deprecated; use 'saved_tensors'
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.4690 Accuracy: 0.1300 Precision: 0.1203 Recall: 0.1250 AUC: 0.8482


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



tensor([[162.,  88.],
        [116., 134.]])
val Loss: 0.7365 Accuracy: 0.1480 Precision: 0.1302 Recall: 0.1387 AUC: 0.6367

Epoch 5/15
----------


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: 'saved_variables' is deprecated; use 'saved_tensors'
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.4339 Accuracy: 0.1330 Precision: 0.1249 Recall: 0.1297 AUC: 0.8722


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



tensor([[207.,  43.],
        [173.,  77.]])
val Loss: 0.9301 Accuracy: 0.1420 Precision: 0.1201 Recall: 0.1388 AUC: 0.6208

Epoch 6/15
----------


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: 'saved_variables' is deprecated; use 'saved_tensors'
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.3755 Accuracy: 0.1383 Precision: 0.1314 Recall: 0.1357 AUC: 0.9080


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



tensor([[185.,  65.],
        [153.,  97.]])
val Loss: 0.9449 Accuracy: 0.1410 Precision: 0.1201 Recall: 0.1333 AUC: 0.6147

Epoch 7/15
----------


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: 'saved_variables' is deprecated; use 'saved_tensors'
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.3647 Accuracy: 0.1397 Precision: 0.1330 Recall: 0.1372 AUC: 0.9132


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



tensor([[189.,  61.],
        [162.,  88.]])
val Loss: 0.9849 Accuracy: 0.1385 Precision: 0.1199 Recall: 0.1354 AUC: 0.6121

Epoch 8/15
----------


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: 'saved_variables' is deprecated; use 'saved_tensors'
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.3566 Accuracy: 0.1393 Precision: 0.1326 Recall: 0.1366 AUC: 0.9167


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



tensor([[186.,  64.],
        [156.,  94.]])
val Loss: 0.9884 Accuracy: 0.1400 Precision: 0.1169 Recall: 0.1298 AUC: 0.6094

Epoch 9/15
----------


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: 'saved_variables' is deprecated; use 'saved_tensors'
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.3538 Accuracy: 0.1407 Precision: 0.1345 Recall: 0.1386 AUC: 0.9180


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



tensor([[184.,  66.],
        [159.,  91.]])
val Loss: 0.9959 Accuracy: 0.1375 Precision: 0.1177 Recall: 0.1318 AUC: 0.6090

Epoch 10/15
----------


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: 'saved_variables' is deprecated; use 'saved_tensors'
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
 import torch
 model = hist['model']
 model.to('cuda')

 def visualize_model(model, num_images=6):
    was_training = model.training
    model.eval()
    images_so_far = 0
    fig = plt.figure()

    with torch.no_grad():
        for sample in dataloaders['val']:
            inputs = sample['image']
            texts = sample['text']
            offsets = sample['mask']
            labels = sample['label']
            inputs = inputs.to(device='cuda')
            texts = texts.to(device='cuda')
            offsets = offsets.to(device='cuda')
            labels = labels.to(device='cuda')
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)

            for j in range(inputs.size()[0]):
                images_so_far += 1
                ax = plt.subplot(num_images//2, 2, images_so_far)
                ax.axis('off')
                print('Label: '+classes[labels[j]])
                print('Predicted: '+classes[preds[j]])
                im = transforms.ToPILImage()(inputs.cpu().data[j]).convert("RGB")
                display(im)

                if images_so_far == num_images:
                    model.train(mode=was_training)
                    return
        model.train(mode=was_training)

In [ ]:
visualize_model(model)

In [ ]:
model.eval()
images_so_far = 0
fig = plt.figure()
id = []
proba=[]
label=[]
tk0 = tqdm(test, total=1000)
with torch.no_grad():
    for i, sample in enumerate(tk0,0):
        name = sample['name']
        inputs = sample['image']
        texts = sample['text']
        offsets = sample['mask']
        inputs = inputs.to(device='cuda')
        #texts = texts.to(device='cuda')
        #offsets = offsets.to(device='cuda')
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)
        #print(np.exp(_.cpu()))
        #print(preds.cpu())
        #print(name)
        id.extend(name)
        proba.append(np.exp(_.cpu().item()))
        label.append(preds.cpu().item())

In [ ]:
ids = []
for i in id:
    i = i.split('/')[1]
    i = i.split('.')[0]
    ids.append(i)


sub = pd.DataFrame({'id': ids, 'proba':proba,'label':label})
probs =[]
for i in range(len(sub)):
    if sub.label[i]==0:
        probs.append(1-sub.proba[i])
    else:
        probs.append(sub.proba[i])
sub.proba = probs
sub.to_csv('subm_img_resnet.csv',index=None)

In [ ]:
torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': loss,
            ...
            }, PATH)

In [ ]:
from pynvml import *
nvmlInit()
h = nvmlDeviceGetHandleByIndex(0)
info = nvmlDeviceGetMemoryInfo(h)
print(f'total    : {info.total}')
print(f'free     : {info.free}')
print(f'used     : {info.used}')